### ISSUE TITLE
replace == with equals

### ISSUE THREAD

**Issue by stiv-yakovenko** [liveontologies/puli#1]
if (step.getName() == AssertedConclusionInference.NAME)

is incorrect and works by luck

**Comment by ykazakov** [comment]
Can you elaborate a bit more? What is the problem?

**Comment by stiv-yakovenko** [comment]
http://stackoverflow.com/questions/513832/how-do-i-compare-strings-in-java

**Comment by ykazakov** [comment]
Anything does not work? You wrote that something works by luck.
Do you have an example when asserted inferences are not removed?
I am aware that .equals() is generally not the same as ==, regardless of the type of objects.

**Comment by stiv-yakovenko** [comment]
Take a look at SO comments. new String("name") == "name" is false, so you should not use such comparisons to avoid UB in future.

**Comment by ykazakov** [comment]
The purpose of this code is to check if the inference step originates from the AssertedConclusionInference, not from any other inference which happens to have the name "Asserted Conclusion".
Besides, String.equals() is much slower than == since to compare two strings one has to individually compare all characters of these string.

**Comment by stiv-yakovenko** [comment]
If strings are same objects, then loop is not executed, if they are different, then 2-3 iterations willl be enough to return false. I just wanted to point out typical bug in java code, if you don't think its a bug, well, its up to you to decide.

**Comment by ykazakov** [comment]
Thanks for your advice. Although it is a typical mistake for novice programmers, in this case it is not a bug as I explained. Further, with equals() there is a higher chance one could get a bug since somebody can accidentally introduce an inference with the name "Asserted Conclusion", which will then be removed. 
If you use a static checker such as "find bugs" and it flags it as a potential problem, we can think about a workaround here.

**Comment by stiv-yakovenko** [comment]
Well, my IDE settings highlighted it :) 
It will work unless someone decides to make deep copy or clone this string, you are right.
Take a look at other ==s if you are concerned :)
